#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# More detailed instructions are available at:
# https://carpentries.github.io/workshop-template/customization/index.html

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
# swc: Software Carpentry
#  dc: Data Carpentry
#  lc: Library Carpentry
#  cp: Carpentries (to use for instructor training for instance)
# Note that for regular workshops, you should use:
#  https://github.com/carpentries/workshop-template
# and for instructor training events you should use:
#  https://github.com/carpentries/training-template
carpentry: "dc"

# This option is currently only needed for
# Data Carpentry and Software Carpentry workshops.
# The value of the variable will be ignored for Library Carpentry
# workshops.
# Possible values are:
# dc-ecology: for Data Carpentry Ecology workshops
# dc-genomics: for Data Carpentry Genomics
# dc-socsci: for Data Carpentry Social Sciences
# dc-geospatial: for Data Carpentry Geospatial
# swc-inflammation: for Software Carpentry based on the inflammation dataset
# swc-gapminder: for Software Carpentry based on the Gapminder dataset
curriculum: "dc-bioinformatics"

# If there is both an R and python official version of a curriculum
# (as listed on https://software-carpentry.org/lessons/ and
# https://datacarpentry.org/lessons/), change the
# value of the variable below ("flavor") to get the schedule and installation
# instructions updated accordingly (valid values are 'r' or 'python').
# Note: this is only for Data Carpentry and SWC at this time.
flavor: "python"

# Overall title for the Workshop.
# This variable is used to (optionally) add a title in the "jumbotron"
# (the grey box at the top of the page), and to the extra pages.
# Most workshops don't use extra pages. More information about extra
# pages are included in the README:
# https://github.com/carpentries/workshop-template#creating-extra-pages
title: "Basic	Bioinformatics	and	command-line	tools	for	
phytopathologists"


#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: rknx/APSBasicBioinformatics

# Email address, no mailto:
# (Don't change this -- the contact address for your workshop will be set
# in the index.md file)
email: "sujan.timilsina@ufl.edu"

# Sites.
baseSite: "https://bioinfoaps.github.io/"
github.url: "https://bioinfoaps.github.io/"
workshop_repo: "https://github.com/BioInfoAPS/BioInfoAPS.github.io"
faq: "faq.html"
survey: "survey.html"
feedback: "feedback.html"
owner: "Anuj Sharma"
ownerLink: "https://anujs.com.np/"


# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/

# Turn on built-in syntax highlighting.
highlighter: rouge
